"""外部会話の保存と検索を外へ任せる口。"""

from __future__ import annotations

from typing import Protocol

from yadori.domain.importing.model import ExternalConversation, ExternalFound, Imported
from yadori.domain.memory.model import Vector


class Archive(Protocol):
    def existing(self, person: str, source: str) -> Imported | None: ...
    def native_exists(self, person: str, source: str) -> bool: ...
    def get(self, person: str, identifier: int) -> Imported | None: ...
    def following(
        self, person: str, conversation: ExternalConversation
    ) -> tuple[Imported, ...]: ...
    def keep(
        self, person: str, conversation: ExternalConversation, model: str, vector: Vector
    ) -> bool: ...
    def search(
        self, person: str, model: str, vector: Vector, floor: float, limit: int
    ) -> tuple[ExternalFound, ...]: ...
    def unindexed(self, person: str, model: str) -> tuple[Imported, ...]: ...
    def index(self, person: str, identifier: int, model: str, vector: Vector) -> None: ...
